apiVersion: v1

kind: Pod

metadata:
  name: nginx-pod
  labels:
    env: prod
    version: v1.2.3
   
spec:  
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80        

