apiVersion: v1

kind: Service

metadata:
  name: nginx-svc
  labels:
    env: prod
    version: v1.2.3

spec:
  selector:
    app: nginx-pod
  
  type: NodePort
  ports:
  - nodePort: 31000        
    port: 80
    targetPort: 80

